version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  lint-test:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/dask-remote
    
    environment:
        PIPENV_VENV_IN_PROJECT: true 

    steps:
      - run:
          name: Update poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            cat $HOME/.poetry/env >> $BASH_ENV

      - checkout

      # - run:
      #     name: Configure Github access
      #     command: |
      #       	git config --global --unset url.ssh://git@github.com.insteadof;\
      #           echo https://${GITHUB_TOKEN}:@github.com > ~/.git-credentials
      #         git config --global credential.helper store

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - pip-cache-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Install dependencies
          command: |
            make install
      
      - save_cache:
          paths:
              - ./.venv/
          key: pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Run lint
          command: |
            make lint

      - run:
          name: Run unit tests
          command: |
            make test TEST_GROUP=unit

      - store_test_results:
          path: ./junit

      # - codecov/upload:
      #     file: ./coverage.xml


workflows:
  version: 2
  lint-test-docs:
    jobs:
      - lint-test
