# https://circleci.com/docs/2.1/language-python/
version: 2.1

# ------------------
# Reusable executors
# ------------------

executors:

  standard:
    docker:
      - image: circleci/python:3.7.6
        environment:
          POETRY_VIRTUALENVS_IN_PROJECT: true
    working_directory: "~/lib"


# -----------------
# Reusable commands
# -----------------

commands:

  update_virtualenv:
    steps:
      - restore_cache:
          keys:
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - virtualenv-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: Install Python packages
          command: make install
      - save_cache:
          key: virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "./.venv"


# --------------
# Pipeline tasks
# --------------

jobs:

  lint:
    executor: standard
    steps:
      - checkout
      - update_virtualenv
      - run:
          name: Run Python linter
          command: make lint

  test:
    executor: standard
    environment:
      TEST_GROUP: "unit"
    steps:
      - checkout
      - update_virtualenv
      - run:
          name: Run Python tests
          command: make test
      - store_test_results:
          path: "."

  build:
    executor: standard
    steps:
      - checkout
      - update_virtualenv
      - run:
          name: Build wheel
          command: make package
      - store_artifacts:
          path: dist
          destination: wheel

  publish:
    executor: standard
    steps:
      - checkout
      - update_virtualenv
      - run:
          name: Publish wheel
          command: make release


# -----------------
# Pipeline workflow
# -----------------

workflows:

  version: 2

  lint-test-build-publish:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
